### ISSUE TITLE
 uninitialized constant `Net::LDAP::LdapError`

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-ldapquery#43]
```
Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, uninitialized constant Net::LDAP::LdapError
```

This error class was deprecated and removed in `net-ldap` `0.17.0` See https://github.com/ruby-ldap/ruby-net-ldap/commit/94b9d4d0443b8be37b91fcb5d6a31a9589cca41a

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-ldapquery/pull/38

**Comment by alexjfisher** [comment]
Yep.  Just seen it.
